### ISSUE TITLE
Readme file needed

### ISSUE THREAD

**Issue by temilaj** [mykeels/CommandLineParser#1]
This looks like an interesting project, but it's a tad difficult to know what it does at first glance. Please provide a readme file an dshare some details.

**Comment by mykeels** [comment]
Hi @temilaj ... 

Yea, I just created the repo today and haven't yet gotten around to writing a readme. 😄  I'll work on it tonight.

Thanks!

Meanwhile, it's a library for extracting information from arguments passed to a program via the command-line.

It's supposed to use generics to return an object containing the extracted information. 

It will be declarative and make use of custom Attributes

**Comment by mykeels** [comment]
1st draft of [README.md](https://github.com/mykeels/CommandLineParser/blob/master/README.md) is up

**Comment by temilaj** [comment]
Just went through it. Seems pretty cool. I should totally try this out.
